export const courseManagement = [
  {
    id: 1,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "live session",
    noOfRegisterStudent: 1_454_342,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 2,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "On Demand Courses",
    noOfRegisterStudent: 1_454_342,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 3,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "live session",
    noOfRegisterStudent: 1_454_342,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 4,
    duration: "may cohort",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "On Demand Courses",
    noOfRegisterStudent: 454_342,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 5,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "live session",
    noOfRegisterStudent: 5_342,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 6,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "live session",
    noOfRegisterStudent: 78,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 7,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "On Demand Courses",
    noOfRegisterStudent: 90,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 8,
    duration: "one month access",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "live session",
    noOfRegisterStudent: 78,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
  {
    id: 9,
    duration: "may cohort",
    title: "Project Consultant Training Programme (Bundle) | May Cohort 2024",
    type: "On Demand Courses",
    noOfRegisterStudent: 78,
    createdAt: "Apr 12, 2023 | 09:32AM",
  },
];
